Fix for rebuilding the gage when it leaves the viewport or is hidden/reshown
frapontillo/angular-gage pull request #17
Opened 2016-11-16 02:33 UTC by dnfield

Adds method to check whether the element is in the viewport - if so, rebuild the justgage to ensure that it animates/displays correctly.  Otherwise, the gage will sometimes not fully redraw.

2016-11-16 11:10 UTC, frapontillo commented on src/directives/justgage.js
> +            watchers.push(scope.$watch(function () { return isElementInViewPort(element[0]); }, function (newValue) {
I have to say I'm not a fan of this approach: recalculating a function at every digest is too expensive, but I also know there are no other alternatives for this.

2016-11-17 17:42 UTC, dnfield commented on src/directives/justgage.js
> +            watchers.push(scope.$watch(function () { return isElementInViewPort(element[0]); }, function (newValue) {
I agree it's not ideal - I couldn't come up with a better way short of getting deeper into the justgage code and reworking how the SVG is animated.  Maybe add a property to allow this watch to be disabled?

2016-11-17 18:17 UTC, frapontillo commented on src/directives/justgage.js
> +            watchers.push(scope.$watch(function () { return isElementInViewPort(element[0]); }, function (newValue) {
YES PLEASE

2016-11-17 20:00 UTC, dnfield commented on src/directives/justgage.js
> +            watchers.push(scope.$watch(function () { return isElementInViewPort(element[0]); }, function (newValue) {
Updated - new attribute, watch-view-port, set to true to set up that watcher, false to not.  It wouldn't response to changes, not 100% sure how I'd make that work

2016-11-18 11:58 UTC, frapontillo requested changes
A few improvements, then good to go.

2016-11-18 11:58 UTC, frapontillo commented on src/directives/justgage.js
> +          function isElementInViewPort(el) {
You already have `element`, don't need an argument here at all.

2016-11-18 11:58 UTC, frapontillo commented on src/directives/justgage.js
> +          scope.$on('$destroy', function handleDestroyEvent() {
You can pass the `destroyJustgage` function as an argument.

2016-11-18 11:58 UTC, frapontillo commented on src/directives/justgage.js
> +              watchers.push(scope.$watch(function () { return isElementInViewPort(element[0]); }, function (newValue) {
By removing the `el` argument to the function `isElementInViewPort` you can pass it as a simple argument to `$watch`.

2016-11-18 11:58 UTC, frapontillo commented on src/directives/justgage.js
> +          var rebuildJustgage = function() {
Please add a blank line before the `rebuildJustgage` function.

2016-12-06 23:45 UTC, dnfield commented
Done, thanks for the feedback.

2018-09-26 21:20 UTC, dnfield commented
Not sure if this project is still alive or anyone's interested - feel free to reopen and merge if you want, I'm just trying to clean up what shows up in my open pulls list :)

2018-09-26 21:20 UTC, closed without merging